### DISCUSSION TITLE
How to change DataGrid Pager active caret color?

### DISCUSSION THREAD

**Discussion by nvassell** [Megabit/Blazorise#1704] [Q&A]
I've really been enjoying the library so far, however, when clicking the items per page dropdown in the material DataGrid the caret color changes to purple and I can't figure out how to change it.

I have tried: 
- Creating a black / white / yellow theme
```cs
@code {
    private Theme theme = new Theme
    {
        BarOptions = new ThemeBarOptions
        {
            // Navbar options
        },
        BackgroundOptions = new ThemeBackgroundOptions
        {
            Primary = "#ffff00", // neon yellow, so it pops better
        },
        BreakpointOptions = new ThemeBreakpointOptions
        {
            // Idk what this one is
        },
        ColorOptions = new ThemeColorOptions
        {
            Primary = "#ffff00", // neon yellow, so it pops better
        },
        TextColorOptions = new ThemeTextColorOptions
        {
            Primary = "#000000", // Black
            Secondary = "#ffffff", // White
        },
        InputOptions = new ThemeInputOptions
        {
            CheckColor = "#ffff00", // newon yellow
        },
    };
} 
```

- Editing elements in `material.css`
- Editing elements in `blazorise.css`
- Editing elements in `blazorise.material.css`

Before:
![image](https://user-images.githubusercontent.com/36028839/104500028-baa69e80-5592-11eb-957c-218682f05a81.png)
After:
![image](https://user-images.githubusercontent.com/36028839/104500116-d5791300-5592-11eb-8478-897cc009fe6d.png)

How do I change the caret color for that dropdown that is circled above? Thanks!

**Comment by stsrki** [comment]
Hmm, I was able to find the styles for the bottom line of the select.

![image](https://user-images.githubusercontent.com/900302/104567022-9d370a80-564e-11eb-88c5-7ae642c0e746.png)

But for caret, I could not find it. It's not even in the shadow DOM. I will need to look at the source of https://github.com/djibe/material to find where it is applied.

**Comment by stsrki** [comment]
Found it! It's controlled by the `background-image` and `svg` image color.

![image](https://user-images.githubusercontent.com/900302/104701025-56f8ae80-5715-11eb-9811-3b37e0dc17c8.png)

**Reply by domn1995** [reply]
I see it now in `_text-field.scss:172`:
```scss
 &:focus { // stylelint-disable-line order/order
      background-image: escape-svg(url('data:image/svg+xml;charset=utf8,<svg fill="#{selection-theme-color()}" transform="rotate(180)" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M7 10l5 5 5-5z"/><animateTransform attributeName="transform" attributeType="XML" type="rotate" from="0 0 0" to="180 0 0" dur="250ms"/></svg>'));
    }
```

Looks like it's grabbing the `svg fill` from `#{selection-theme-color()}`. 

Sorry I'm not too familiar with the library. Is this value something we can edit client-side or does Blazorise need to push a change for that caret to be affected by the theming API?
