### DISCUSSION TITLE
Listview item background

### DISCUSSION THREAD

**Discussion by blenke** [Megabit/Blazorise#5537] [Q&A]
I would like to highlight items on a listview based on the Context.Item value . Is that possible ? I can create a div inside the itemtemplate and give it a color but this doesn't cover the entire item and leaves a white border.

**Comment by stsrki** [comment]
You can try setting the custom CSS class on a ListView to remove padding from the items

`<ListView Class="custom-items"`

and then define a selector 

```css
.list-group.custom-items .list-group-item
{
  padding: 0;
  background-color: red;
}
```
