### ISSUE TITLE
Button Text case not working when button has an Icon

### ISSUE THREAD

**Issue by WillianGruber** [Megabit/Blazorise#1170]
Hi,

Refering to #446,
Using material, with Casing="CharacterCasing.Title" applies text-transform:lowercase to the button text.
Can this be fixed?
Also, can "normal" mode be changed from provider's default to crude/direct text? With "normal" in material setting the text upppercase it is impossible to have a button with text "abc Def".

Thanks!

**Comment by stsrki** [comment]
It actually applies

```scss
.b-character-casing-title {
    text-transform: lowercase;

    &::first-letter {
        text-transform: uppercase;
    }
}
```

Which means all letters except first will be lowercase.
