### ISSUE TITLE
Create services for messages and notifications

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#1634]
The idea is to have a set of components and helper services based on the core Blazorise components

## IMessageService

An injected service that will show modal simply by calling a `messageService.Show("This is message", "Custom title")`. Internally it will be based on the **Modal** dialog

## INotificationService

Similar to `IMessageService`, but this will show a toast message instead of full-screen message.

## IPageProgressService

Service that will show a progress bar at the top of the screen. Internally it will be based on PageProgress component.

**Comment by kamilkosek** [comment]
I love the idea of implementing the services inside core Blazorise. 
Currently I am using many 3rd party Components like for example [https://github.com/Blazored/Toast](https://github.com/Blazored/Toast) and whenever there is an update (blazorise or others) it breaks something. 

In a project I am working on, I´ve implemented a quick and dirty "LoadingService" which just shows an overlay with a progress bar.

Maybe the snippets could help someone: 
LoadingService:
```csharp
public class LoadingService
    {
        public event Action<string> OnSetMessage;

        public event Action OnShow;
        public event Action OnHide;
        public void Show()
        {
            OnShow?.Invoke();
        }
        public void Show(string message)
        {
            Show();
            SetMessage(message);
        }
        public void Hide()
        {
            OnHide?.Invoke();
        }
        public void SetMessage(string message)
        {
            OnSetMessage?.Invoke(message);
        }
        public void ClearMessage()
        {
            OnSetMessage?.Invoke(string.Empty);
        }
    }
```
LoadingComponent.razor
```csharp
@if (IsLoading)
{
    <div class="loader-modal">
        <div class="loader-modal-content">
            <BlazorPro.Spinkit.Wave Color="rgb(224, 11, 11)"></BlazorPro.Spinkit.Wave>
            @if(!string.IsNullOrEmpty(Message))
            {
                <div class="text-lg-left text-dark">@Message</div>
            }
        </div>
    </div>
}

@code {

}
```
LoadingComponent.razor.cs
```csharp
public partial class LoadingComponent
    {
        [Inject]
        public LoadingService LoadingService { get; set; }
        bool IsLoading;
        string Message = "";
        protected override void OnInitialized()
        {
            LoadingService.OnShow += Show;
            LoadingService.OnHide += Hide;
            LoadingService.OnSetMessage += SetMessage;
        }
        private void Show()
        {
            InvokeAsync(() =>
            {
                Message = string.Empty;
                IsLoading = true;
                StateHasChanged();
            });
        }
        private void Hide()
        {
            InvokeAsync(() =>
            {
                IsLoading = false;
                Message = string.Empty;
                StateHasChanged();
            });
        }
        private void SetMessage(string message)
        {
            InvokeAsync(() =>
            {
                Message = message;
                StateHasChanged();
            });
        }
    }
```
CSS
```css
.loader-modal {
    position: fixed; /* Stay in place */
    z-index: 10000; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.3); /* Black w/ opacity */
}
.loader-modal-content {
    position: fixed;
    left: 50%;
    top: 50%;
    z-index: 10001;
}
```
