### ISSUE TITLE
DataGrid pager styling changed in 0.9.4

### ISSUE THREAD

**Issue by naefp** [Megabit/Blazorise#2679]
**Describe the bug**
Not sure if this is a bug or planned to work like that.

With updating Blazorise to `0.9.4` the styling of the DataGrid pager changed. In previews version the page-link elements inherited the color, now I had to add something like that to get back the old behavior:
```css
/* old behavior for pager style after DataGrid update */
.page-link, .page-link:hover {
    color: inherit;
}
```

just close the issue, if that was done on purpose.
