### ISSUE TITLE
Best practices for changing the style of child component?

### ISSUE THREAD

**Issue by rwecho** [Megabit/Blazorise#4266]
For example, the DropDownList component contains a DropDownMenu child component. To the DropDownList we can change the style by the class or style. But for the child component, there is no friendly way to modify its style.

Now I resolve it through the DropDownList class:

``` XAML
<!-- index.razor -->
<div>  <!-- important, without it the CSS ::deep not working -->
    <DropDownList  Data...  Class="dropdown-list">
    </DownloadList>
</div>

```
``` CSS
/* index.razor.css */
::deep .dropdown-list .dropdown-menu
{
    overflow-y: auto;
}
```

Is there any better to achieve this aim?  like this:

``` XAML
<DropDownlist  MenuStyle="" >
<DownDownlist>
```

Thanks.
