### ISSUE TITLE
Add text highlighting to `MemoEdit`

### ISSUE THREAD

**Issue by Jinjinov** [Megabit/Blazorise#4574]
**Is your feature request related to a problem? Please describe.**

It is not possible to highlight search results inside `MemoEdit`

**Describe the solution you'd like**

Support several different ways to highlight text - at least `string` and `Range` - (perhaps also `RexEx` and `Predicate`)

### Additional context

- https://codersblock.com/blog/highlight-text-inside-a-textarea/
- https://codepen.io/lonekorean/pen/gaLEMR
- https://lonekorean.github.io/highlight-within-textarea/
- https://github.com/lonekorean/highlight-within-textarea

**Comment by stsrki** [comment]
It seems like a neat feature to have, but we will not be able to make it. From what I can find, all the examples are in jQuery, or the projects are not maintained anymore. The best so far is https://github.com/masterWeber/highlight-in-textarea, but even that is last updated two years ago.

**Comment by Jinjinov** [comment]
I created it myself and it works just like I want it to.

You can test it at https://new.ididit.today/
- choose `[ ] Show advanced input`
- choose `[ ] Select line with caret`
- choose `[ ] Filter by selected text`
- type `task` in the MemoEdit
- click on `Change these notes to tasks` to enable the other MemoEdit - it will have the word `task` highlighted.

Here are the instructions:

This is the css:

```css
    .hwt-mark {
        color: transparent !important;
    }

    .hwt-backdrop {
        z-index: 1;
    }

    .hwt-textarea {
        z-index: 2;
        background-color: transparent !important;
    }

    .hwt-highlights {
        color: transparent !important;
        white-space: pre-wrap;
        letter-spacing: normal;
    }
```

The razor accepts `string MemoEditText` and `string HighlightText`, the `form-control` is from Bootstrap:

```razor
    <Div>
        <Div class="hwt-backdrop" Position="Position.Absolute" Width=Width.Is100>
            <Div class="hwt-highlights form-control">
                @((MarkupString)MarkHighlightText(MemoEditText))
            </Div>
        </Div>
        <MemoEdit Class="hwt-textarea" Position="Position.Relative" AutoSize Text="@MemoEditText" />
    </Div>
```

This is the C#

```csharp
    string MarkHighlightText(string text)
    {
        return text.Replace(HighlightText, $"<mark class='hwt-mark'>{HighlightText}</mark>");
    }
```

There are only 2 thing missing from the https://github.com/lonekorean/highlight-within-textarea / https://codepen.io/lonekorean/pen/gaLEMR version

- there is no `fixIOS` and `fixFirefox`, but `normalize.css` takes care of that https://getbootstrap.com/docs/5.0/content/reboot/
- my `MemoEdit` has `AutoSize`, so I don't need to handle scrolling

```js
  var $backdrop = $('.backdrop');
  var $textarea = $('textarea');

  function handleScroll() {
    var scrollTop = $textarea.scrollTop();
    $backdrop.scrollTop(scrollTop);
  
    var scrollLeft = $textarea.scrollLeft();
    $backdrop.scrollLeft(scrollLeft);  
  }

  $textarea.on({
    'scroll': handleScroll
  });
```
