### ISSUE TITLE
Overlaping video players

### ISSUE THREAD

**Issue by thumaman** [Megabit/Blazorise#5456]
Is it possible to overlap video players, to have one small video playing on top of the main one?

It seems that anything i try, the smaller video is always displayed to the side of the main one so that they do not overlap.

**Comment by stsrki** [comment]
Do you mean like a picture-in-picture?

**Comment by thumaman** [comment]
Sort of, in trying to display videos with educational content and want to add a feature for sign language. I have the video of the person speaking sing languege with transparent background and want to put them in the bottom right corner over of the educational video.
I thought the best way would be to have two synced video players and just position one over the other but I cannot make it work.
Do you have any recommendations?

**Comment by stsrki** [comment]
That should be fairly easy with CSS i believe. Have a container div with `position: relative;` and then you can have videos inside od another div each, with `position: absolute;`.

```html
<div class="main-videos-container">
  <div class="video-1">  
     ..
  </div>
  <div class="video-1">  
     ..
  </div>  
</div>
```

**Comment by David-Moreira** [comment]
Although you can most likely make it work with html positioning as @stsrki mentioned.

I wonder if in the long run, it's better to avoid any issues that could perhaps occur with having to keep both videos synced?

And if it would be better to have an additional video file with the sign language imbued that will load instead if the user requests to view with sign language.
That is, if that is possible/feasible for you.

**Comment by stsrki** [comment]
```css
.main-videos-container {
  position: relative;
}

.video-1 {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}

.video-2 {
  position: absolute;
  bottom: 0;
  right: 0;
  width: 200px;
  height: 100px;
}
```

Haven't tried it but it should give you an idea.
