### ISSUE TITLE
[HELP] disable succes Validation styling

### ISSUE THREAD

**Issue by Hyppothalamus** [Megabit/Blazorise#5892]
Hello,

I am writing a modal form with Blazorise Validation component. I like the styling when a field has an error but is their a way to disable the green styling when a field is fixed or from initialize there a no errors?

I searched trough the docs and issues and I couldn't find anything related to this. Or is this not possible?

Thanks in advance for the help!

**Comment by stsrki** [comment]
At the moment, this is only possible with custom CSS.

Try this:

```css
.form-control.is-valid, .was-validated .form-control:valid {
    border-color: unset;
}
```
